### ISSUE TITLE
BPF程序加载失败

### ISSUE THREAD

**Issue by myzhan** [findstr/lua-perf#2]
运行的时候，直接 panic 了，把 debug 模式打开，拿到下面的日志

```bash
libbpf: prog 'profile': failed to load: -13
```

环境：
1. ubuntu 22.04
2. clang 14

**Comment by findstr** [comment]
现在我手头没有相似的环境，周末我造个环境试一下。

**Comment by findstr** [comment]
能不能提供一下内核版本，谢谢。

**Comment by myzhan** [comment]
内核版本 6.8.0-40

**Comment by findstr** [comment]
由于网络问题，我没有复刻与你完全一致的环境。
我安装了`Ubuntu 24.04.1 LTS`, `6.8.0-45-generic`, `clang-18`，没有重现你的报错。
不过我查了一下错误码，`errno=13` 似乎代表了权限问题。

**Comment by myzhan** [comment]
我的 clang-14 是 ubuntu 源里面的，我试试 llvm 源里面的 clang-18

**Comment by myzhan** [comment]
用 clang-18 可以跑了，怀疑是 clang-14 生成的字节码被 verifier 给拒了。不过运行后遇到其他问题，我单开 issue 记录吧。

**Comment by findstr** [comment]
好的
